# Generated by Django 5.0.1 on 2024-02-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0003_remove_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pos_app.business'),
            preserve_default=False,
        ),
    ]
